name: pagila

config-version: 2
version: '1.3.0'

profile: pagila

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  pagila:
      staging:
        +materialized: view
